//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusPassWithQRScanEntities : DbContext
    {
        public BusPassWithQRScanEntities()
            : base("name=BusPassWithQRScanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Bus> Buses { get; set; }
        public virtual DbSet<Conductor> Conductors { get; set; }
        public virtual DbSet<FavouriteStop> FavouriteStops { get; set; }
        public virtual DbSet<IsAssigned> IsAssigneds { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Pass> Passes { get; set; }
        public virtual DbSet<Reach> Reaches { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteSharing> RouteSharings { get; set; }
        public virtual DbSet<RouteStop> RouteStops { get; set; }
        public virtual DbSet<Start> Starts { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TracksLocation> TracksLocations { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
