//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        public int id { get; set; }
        public Nullable<System.TimeSpan> stoptiming { get; set; }
        public Nullable<int> route_id { get; set; }
        public Nullable<int> stop_id { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Stop Stop { get; set; }
    }
}
