//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHistory
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string type { get; set; }
        public Nullable<int> student_passid { get; set; }
        public Nullable<int> bus_busno { get; set; }
        public Nullable<int> stop_id { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Stop Stop { get; set; }
        public virtual Student Student { get; set; }
    }
}
